/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
/* automatically generated by rust-bindgen 0.69.2 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct postjectee_options {
    pub elf_section_name: *const ::std::os::raw::c_char,
    pub macho_section_name: *const ::std::os::raw::c_char,
    pub macho_segment_name: *const ::std::os::raw::c_char,
    pub pe_resource_name: *const ::std::os::raw::c_char,
}
extern "C" {
    pub fn postjectee_find_resource(
        name: *const ::std::os::raw::c_char,
        size: *mut usize,
        options: postjectee_options,
    ) -> *const ::std::os::raw::c_void;
}
