/* automatically generated by rust-bindgen 0.69.2 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct postjectee_options {
    pub elf_section_name: *const ::std::os::raw::c_char,
    pub macho_section_name: *const ::std::os::raw::c_char,
    pub macho_segment_name: *const ::std::os::raw::c_char,
    pub pe_resource_name: *const ::std::os::raw::c_char,
}
extern "C" {
    pub fn postjectee_find_resource(
        name: *const ::std::os::raw::c_char,
        size: *mut usize,
        options: postjectee_options,
    ) -> *const ::std::os::raw::c_void;
}
