name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            target: x86_64-pc-windows-msvc
          - os: windows-2019
            target: i686-pc-windows-msvc
          - os: windows-2019
            target: aarch64-pc-windows-msvc
            build_only: true
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            build_only: true
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build_only: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@1.75.0
    - name: Enable VS Dev Prompt
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.target == 'i686-pc-windows-msvc'
    - name: Install 32-bit LLVM
      run: choco install llvm --forcex86 --force
      if: matrix.target == 'i686-pc-windows-msvc'
    - name: Install gcc-multilib for cross-bindgen
      run: sudo apt-get install -y gcc-multilib
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      shell: bash
      id: build
      run: |
        rustup target add ${{ matrix.target }}
        cargo build --target ${{ matrix.target }} --release --all-features --verbose
        zipname=$(python3 scripts/ci_build_cli.py ${{ matrix.target }})
        echo "::set-output name=zipname::$zipname"
    - name: Upload editres_cli
      uses: actions/upload-artifact@v4
      with:
        name: editres_cli_-${{ matrix.target }}
        path: ${{ steps.build.outputs.zipname }}
    - name: Run tests
      run: cargo test --target ${{ matrix.target }} --release --all --all-features --verbose
      if: matrix.build_only != true
