name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            target: x86_64-pc-windows-msvc
          - os: windows-2019
            target: i686-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@1.75.0
    - name: Enable VS Dev Prompt
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.target == 'i686-pc-windows-msvc'
    - name: Install 32-bit LLVM
      run: choco install llvm --forcex86 --force
      if: matrix.target == 'i686-pc-windows-msvc'
    - name: Install gcc-multilib for cross-bindgen
      run: sudo apt-get install -y gcc-multilib
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      run: |
        rustup target add ${{ matrix.target }}
        cargo build --target ${{ matrix.target }} --release --all-features --verbose
    - name: Run tests
      run: cargo test --target ${{ matrix.target }} --release --all --all-features --verbose
  