name: GitHub Release


on:
  push:
    tags:
      - editres_cli-v*

jobs:
  editres_cli_release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: ci.yml
        path: artifacts
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
