name: Publish

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        required: false

jobs:
  cargo-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: ci.yml
        path: ${{ runner.temp }}/artifacts
        run_id: ${{ github.event.inputs.artifact_run_id }} 
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-release@0.25.4
    - name: cargo release
      id: release
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "branchseer"
        cargo release --workspace --exclude testbin --unpublished --all-features --allow-branch '*' --no-verify --execute --no-confirm
        echo new_tags=$(git tag --points-at HEAD) >> $GITHUB_OUTPUT
    - name: GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.release.outputs.new_tags }}
        artifacts: "${{ runner.temp }}/artifacts/*"
