name: Publish

on:
  workflow_dispatch

jobs:
  cargo-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-release@0.25.4
    - name: cargo release
      run: |
        git config --global user.email "dk4rest@gmail.com"
        git config --global user.name "branchseer"
        cargo release --workspace --exclude testbin --unpublished --all-features --no-verify --execute --no-publish --no-confirm
