name: Publish

on:
  workflow_dispatch

jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-release@0.25.4
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: ci.yml
    - name: cargo release
      run: cargo release --workspace --exclude testbin --unpublished --all-features --no-verify --execute --no-publish --no-confirm --token ${{ secrets.CRATES_IO_TOKEN }}
