name: Publish

on:
  workflow_dispatch:
    inputs:
      bumplevel:
        description: cargo-release bump level
        required: true
        default: 'release'

jobs:
  build_cli:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            target: x86_64-pc-windows-msvc
          - os: windows-2019
            target: i686-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: |
        rustup target add ${{ matrix.target }}
        zipname=$(python3 scripts/ci_build_cli.py ${{ matrix.target }})
        echo "::set-output name=zipname::$zipname"
      id: build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.zipname }}
        path: ${{ steps.build.outputs.zipname }}
